name: Activity Filters
on:
  workflow_dispatch:
  pull_request:
    types: [synchronize]

jobs:
  any-old-job:
    runs-on: ubuntu-latest

    steps:
      - name: Any old step
        run: echo "hehe"